### ISSUE TITLE
Create an abbreviations document

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#12]
As a team unfamiliar with client's data, we will need to create a list of abbreviations that can be submitted to and defined by client.

**Comment by KristinJJ** [comment]
Hi @CourtneyHoppus , thanks for self-assigning yourself this issue! 

The abbreviations/acronyms we are looking to clarify would be pertaining to the files linked in this document (https://docs.google.com/document/d/1gG_wCs-utYkdQjR1MJ93uX116BzbG9Z1/edit). 

The abbreviations/acronyms should partially be able to be found out from the info sources. But for the abbreviations/acronyms unable to be found from the info sources, the abbreviations/acronyms document will be submitted to Lawrence so he can provide clarification. 

If you can create the abbreviations/acronyms document in the ad470 Google Drive for easy access that would great, thanks!
