### ISSUE TITLE
Vote Part 2 4/22 or 4/23

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#26]
As a team, we will need to vote on the top 2 or 3 secondary projects in our weekly team meeting.

**Comment by ariunzayaE** [comment]
https://www.kaggle.com/competitions/titanic
https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques
These 2 are my votes.

**Comment by KristinJJ** [comment]
I vote for either this Kaggle competition (https://www.kaggle.com/competitions/titanic) or to continue with the client project
