### ISSUE TITLE
Add Tableau doc to repository

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#28]
As a team of developers, we will need to add our shared Tableau document to the repository so that team member can work on issues asynchronously with version control.

**Comment by KristinJJ** [comment]
From looking at the different Tableau file types, it seems like a Packaged Workbook (.twbx extension) might be the best option for this issue? https://help.tableau.com/current/pro/desktop/en-us/environ_filesandfolders.htm
