### ISSUE TITLE
Add raw csv and Excel files to repository

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#29]
As a team of data scientists, we will need access to the raw data files that our client has provided in the Google Drive file: [description_of_files_for_csed_analytics.docx](https://docs.google.com/document/d/1gG_wCs-utYkdQjR1MJ93uX116BzbG9Z1/edit). Therefore, I will add the raw files to the repo.

**Comment by KristinJJ** [comment]
Hi @brandondombrowsky , are you volunteering for this issue? If so, you can assign yourself as the assignee for this issue for tracking purposes :)

**Comment by KristinJJ** [comment]
Or if you weren't intending on assigning yourself this issue, I can take it on!

**Comment by ariunzayaE** [comment]
I took this issue and just have committed the changes.
