### ISSUE TITLE
Duplicate existing client visualization Option 1 - State-Specific Computer Science Education Scorecards (2022)

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#30]
As a data scientist, reproducibility is a key indicator of accurate results. Therefore, I will attempt to recreate a visualization using Tableau already displayed on client site. This will be a different visualization than Option 2.

If I am able to recreate the chosen visualization, I will take a screenshot and post it to the group Slack thread. If I am unable to recreate the visualization, I will bring the problems I uncovered to the group meeting for discussion.

**Comment by KristinJJ** [comment]
https://cranidores.org/state-specific-computer-science-education-scorecards-2022-now-available/

**Comment by LucasKnezevich** [comment]
https://public.tableau.com/app/profile/lucas.knezevich/viz/2022UnitedStatesComputerScienceEducationScorecard/2022Scorecard?publish=yes
