### ISSUE TITLE
Duplicate existing client visualization Option 2 - The Effect of Policy on CS Education Success Metrics (Part Two)

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#31]
As a data scientist, reproducibility is a key indicator of accurate results. Therefore, I will attempt to recreate a visualization using Tableau already displayed on client site. This will be a different visualization than Option 1.

If I am able to recreate the chosen visualization, I will take a screenshot and post it to the group Slack thread. If I am unable to recreate the visualization, I will bring the problems I uncovered to the group meeting for discussion.

**Comment by KristinJJ** [comment]
https://cranidores.org/the-effect-of-policy-on-cs-education-success-metrics-part-ii/

**Comment by KristinJJ** [comment]
Closing as client does not want to include policy in the Dashboard
