### ISSUE TITLE
Duplicate existing client visualization Option 4 - AP CS Principles: A Cultural shift in K12 CS Education

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#37]
As a data scientist, reproducibility is a key indicator of accurate results. Therefore, I will attempt to recreate a visualization using Tableau already displayed on client site. This will be a different visualization than Option 1.

If I am able to recreate the chosen visualization, I will take a screenshot and post it to the group Slack thread. If I am unable to recreate the visualization, I will bring the problems I uncovered to the group meeting for discussion.

**Comment by KristinJJ** [comment]
https://cranidores.org/ap-cs-principles-a-cultural-shift-in-k12-cs-education/
