### ISSUE TITLE
Duplicate existing client visualization Option 5 - The Effect of Policy on CS Education Success Metrics (Part One)

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#38]
As a data scientist, reproducibility is a key indicator of accurate results. Therefore, I will attempt to recreate a visualization using Tableau already displayed on client site. This will be a different visualization than Option 1.

If I am able to recreate the chosen visualization, I will take a screenshot and post it to the group Slack thread. If I am unable to recreate the visualization, I will bring the problems I uncovered to the group meeting for discussion.

**Comment by KristinJJ** [comment]
https://cranidores.org/the-effect-of-policy-on-cs-education-success-metrics-part-one/

**Comment by ariunzayaE** [comment]
![zaya-part2](https://user-images.githubusercontent.com/81658998/233741164-185201e5-ce75-4029-8ae9-49c21076dc2b.png)
I created duplication. Cannot upload to the cloud workbook.

**Comment by KristinJJ** [comment]
Closing as client does not want to include policy in the Dashboard
