### ISSUE TITLE
Duplicate existing client visualization Option 6 - Hispanic-Latinx Students in HS CS: Little Gaps Everywhere

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#39]
As a data scientist, reproducibility is a key indicator of accurate results. Therefore, I will attempt to recreate a visualization using Tableau already displayed on client site. This will be a different visualization than Option 1.

If I am able to recreate the chosen visualization, I will take a screenshot and post it to the group Slack thread. If I am unable to recreate the visualization, I will bring the problems I uncovered to the group meeting for discussion.

**Comment by KristinJJ** [comment]
https://cranidores.org/hispanic-latinx-students-in-hs-cs-little-gaps-everywhere/
