### ISSUE TITLE
Year to Year Analysis - Option 2 -  Compare 2021_State_of_CS_data and 2022_state_of_cs_data OverallStateData sheet

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#41]
As a data scientist, I will need to compare data from one year to the next in various categories.

**Comment by KristinJJ** [comment]
Compare 2021_State_of_CS_data.xlsx OverallStateData sheet, with 2022_state_of_cs_data.xlsx OverallStateData sheet

**Comment by KristinJJ** [comment]
https://kb.tableau.com/articles/howto/creating-year-over-year-ytd-comparison
