### ISSUE TITLE
Dummy Dashboard Dev 1 - 

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#44]
As a data scientist, it will be important for me to create a singular place for my results that speak to the stakeholders/target audience involved.

**Comment by KristinJJ** [comment]
https://help.tableau.com/current/pro/desktop/en-us/dashboards_create.htm

**Comment by ariunzayaE** [comment]
![Image](https://user-images.githubusercontent.com/81658998/233750750-98fad74a-87f3-4242-bcf9-f9cefa1b0755.png)
