### ISSUE TITLE
Add Abbreviation Intel to Wiki

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#47]
As a team of data scientists, we will need to add the client's abbreviation conventions to our GH Wiki to make sure we are all on the same page. This will also help us make sure we are catering to our "audience".

**Comment by KristinJJ** [comment]
https://github.com/KristinJJ/Cranidores/wiki/Abbreviations-and-Acronyms

**Comment by CourtneyHoppus** [comment]
This issue was started. I documented the major data source files and the columns contained within and where calculations for those data points were made. Issue may need to be continued in the future as seems fit.
