### ISSUE TITLE
PR Naming Convention to Wiki

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#66]
As a co-project manager, I will add a brief description to the Wiki for completing a PR. It will include:

- [x] Headline
- [x] Brief Summary
- [x] Example of how to add text to link PR to corresponding Issue(s)

**Comment by KristinJJ** [comment]
Created wiki page with naming conventions, brief summary of how to create a PR, and example of how to add text to link PR to corresponding issue(s) https://github.com/KristinJJ/Cranidores/wiki/Branches-and-PRs
