### ISSUE TITLE
Duplicate existing client visualization Option 7 - Revisiting the CS HS: Bigger, Faster, and More Suburban

### ISSUE THREAD

**Issue by KristinJJ** [KristinJJ/Cranidores#68]
As a data scientist, reproducibility is a key indicator of accurate results. Therefore, I will attempt to recreate a visualization using Tableau already displayed on client site. This will be a different visualization than Option 1.

If I am able to recreate the chosen visualization, I will take a screenshot and post it to the group Slack thread. If I am unable to recreate the visualization, I will bring the problems I uncovered to the group meeting for discussion.

**Comment by KristinJJ** [comment]
https://cranidores.org/revisiting-the-cs-hs-bigger-faster-and-more-suburban/

**Comment by ariunzayaE** [comment]
![Image](https://user-images.githubusercontent.com/81658998/235574705-8512b2a2-5ed2-46ff-afdc-adc05ca40b28.png)

**Comment by ariunzayaE** [comment]
Owner already created those histogram and chart. So no longer needed.
