### ISSUE TITLE
Duplicate existing client visualization 10 - Blacks in HS CS: Blame AP Envy!

### ISSUE THREAD

**Issue by KristinJJ** [KristinJJ/Cranidores#75]
As a data scientist, reproducibility is a key indicator of accurate results. Therefore, I will attempt to recreate a visualization using Tableau already displayed on client site. This will be a different visualization than Option 1.

If I am able to recreate the chosen visualization, I will take a screenshot and post it to the group Slack thread. If I am unable to recreate the visualization, I will bring the problems I uncovered to the group meeting for discussion.

**Comment by KristinJJ** [comment]
https://cranidores.org/blacks-in-hs-cs-blame-ap-envy/

**Comment by ariunzayaE** [comment]
![Image](https://user-images.githubusercontent.com/81658998/236590162-30978692-3577-491a-bd36-dae9820ce042.png)

**Comment by ariunzayaE** [comment]
Made duplication but It should be vertical but could not make it vertical.

**Comment by ariunzayaE** [comment]
![Image](https://user-images.githubusercontent.com/81658998/236923907-5bcb7349-ad9d-4a89-bf45-5dbfa6bff242.png)

Update!
