### ISSUE TITLE
Add current Dashboard to GitHub along with Tableau Public link

### ISSUE THREAD

**Issue by brandondombrowsky** [KristinJJ/Cranidores#82]
As a co-TPM, I will need to make sure my group's dashboard makes it into the GitHub repo so that the client has access to it.

**Comment by KristinJJ** [comment]
Added link to the Tableau Publiz Viz
 (https://public.tableau.com/app/profile/kristin.jue/viz/Cranidores470_16837830450670/Story1?publish=yes) to Github repo! <img width="372" alt="Screen Shot 2023-05-13 at 12 43 35 AM" src="https://github.com/KristinJJ/Cranidores/assets/26866132/29ab9cd7-2a9e-42c2-8827-c31ea4b29cb0">
